In [8]:
!pip install labelImg

In [9]:
!pip install opencv-python

# Import libraries

In [6]:
import cv2
import os
import numpy as np
import math

# create frames from videos 

In [11]:
def save_all_frames(video_path, dir_path, basename, ext='jpg'):
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        return

    os.makedirs(dir_path, exist_ok=True)
    base_path = os.path.join(dir_path, basename)

    digit = len(str(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))))

    n = 0

    while True:
        ret, frame = cap.read()
        if ret:
            cv2.imwrite('{}_{}.{}'.format(base_path, str(n).zfill(digit), ext), frame)
            n += 1
        else:
            return

save_all_frames('pig_videos/Event20230919160512004.avi', 'pig_videos/Event20230919160512004/', 'sample_video_img')

[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff049c55a80] slice type 32 too large at 132120575
[h264 @ 0x7ff049c55a80] decode_slice_header error
[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[

[h264 @ 0x7ff049ca5600] slice type 32 too large at 132120575
[h264 @ 0x7ff049ca5600] decode_slice_header error
[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049cba900] slice type 32 too large at 132120575
[h264 @ 0x7ff049cba900] decode_slice_header error
[h264 @ 0x7ff049cc5300] slice type 32 too large at 132120575
[h264 @ 0x7ff049cc5300] decode_slice_header error
[h264 @ 0x7ff049ccfcc0] slice type 32 too large at 132120575
[h264 @ 0x7ff049ccfcc0] decode_slice_header error
[h264 @ 0x7ff04ba51bc0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba51bc0] decode_slice_header error
[h264 @ 0x7ff041d7dbc0] slice type 32 too large at 132120575
[h264 @ 0x7ff041d7dbc0] decode_slice_header error
[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[h264 @ 0x7ff041ca9240] slice type 32 too large at 132120575
[h264 @ 0x7ff041ca9240] decode_slice_header error
[

[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049cba900] slice type 32 too large at 132120575
[h264 @ 0x7ff049cba900] decode_slice_header error
[h264 @ 0x7ff049cc5300] slice type 32 too large at 132120575
[h264 @ 0x7ff049cc5300] decode_slice_header error
[h264 @ 0x7ff049ccfcc0] slice type 32 too large at 132120575
[h264 @ 0x7ff049ccfcc0] decode_slice_header error
[h264 @ 0x7ff04ba51bc0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba51bc0] decode_slice_header error
[h264 @ 0x7ff041d7dbc0] slice type 32 too large at 132120575
[h264 @ 0x7ff041d7dbc0] decode_slice_header error
[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[h264 @ 0x7ff041ca9240] slice type 32 too large at 132120575
[h264 @ 0x7ff041ca9240] decode_slice_header error
[

[h264 @ 0x7ff041d7dbc0] slice type 32 too large at 132120575
[h264 @ 0x7ff041d7dbc0] decode_slice_header error
[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[h264 @ 0x7ff041ca9240] slice type 32 too large at 132120575
[h264 @ 0x7ff041ca9240] decode_slice_header error
[h264 @ 0x7ff041cb3a80] slice type 32 too large at 132120575
[h264 @ 0x7ff041cb3a80] decode_slice_header error
[h264 @ 0x7ff04ba05480] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba05480] decode_slice_header error
[h264 @ 0x7ff04ba517c0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba517c0] decode_slice_header error
[h264 @ 0x7ff049ca5600] slice type 32 too large at 132120575
[h264 @ 0x7ff049ca5600] decode_slice_header error
[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049cba900] slice type 32 too large at 132120575
[h264 @ 0x7ff049cba900] decode_slice_header error
[

[h264 @ 0x7ff041cb3a80] slice type 32 too large at 132120575
[h264 @ 0x7ff041cb3a80] decode_slice_header error
[h264 @ 0x7ff04ba05480] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba05480] decode_slice_header error
[h264 @ 0x7ff04ba517c0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba517c0] decode_slice_header error
[h264 @ 0x7ff049ca5600] slice type 32 too large at 132120575
[h264 @ 0x7ff049ca5600] decode_slice_header error
[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049cba900] slice type 32 too large at 132120575
[h264 @ 0x7ff049cba900] decode_slice_header error
[h264 @ 0x7ff049cc5300] slice type 32 too large at 132120575
[h264 @ 0x7ff049cc5300] decode_slice_header error
[h264 @ 0x7ff049ccfcc0] slice type 32 too large at 132120575
[h264 @ 0x7ff049ccfcc0] decode_slice_header error
[h264 @ 0x7ff04ba51bc0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba51bc0] decode_slice_header error
[

[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049cba900] slice type 32 too large at 132120575
[h264 @ 0x7ff049cba900] decode_slice_header error
[h264 @ 0x7ff049cc5300] slice type 32 too large at 132120575
[h264 @ 0x7ff049cc5300] decode_slice_header error
[h264 @ 0x7ff049ccfcc0] slice type 32 too large at 132120575
[h264 @ 0x7ff049ccfcc0] decode_slice_header error
[h264 @ 0x7ff04ba51bc0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba51bc0] decode_slice_header error
[h264 @ 0x7ff041d7dbc0] slice type 32 too large at 132120575
[h264 @ 0x7ff041d7dbc0] decode_slice_header error
[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[h264 @ 0x7ff041ca9240] slice type 32 too large at 132120575
[h264 @ 0x7ff041ca9240] decode_slice_header error
[h264 @ 0x7ff041cb3a80] slice type 32 too large at 132120575
[h264 @ 0x7ff041cb3a80] decode_slice_header error
[

[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[h264 @ 0x7ff041ca9240] slice type 32 too large at 132120575
[h264 @ 0x7ff041ca9240] decode_slice_header error
[h264 @ 0x7ff041cb3a80] slice type 32 too large at 132120575
[h264 @ 0x7ff041cb3a80] decode_slice_header error
[h264 @ 0x7ff04ba05480] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba05480] decode_slice_header error
[h264 @ 0x7ff04ba517c0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba517c0] decode_slice_header error
[h264 @ 0x7ff049ca5600] slice type 32 too large at 132120575
[h264 @ 0x7ff049ca5600] decode_slice_header error
[h264 @ 0x7ff049caff00] slice type 32 too large at 132120575
[h264 @ 0x7ff049caff00] decode_slice_header error
[h264 @ 0x7ff049cba900] slice type 32 too large at 132120575
[h264 @ 0x7ff049cba900] decode_slice_header error
[h264 @ 0x7ff049cc5300] slice type 32 too large at 132120575
[h264 @ 0x7ff049cc5300] decode_slice_header error
[

[h264 @ 0x7ff049cc5300] slice type 32 too large at 132120575
[h264 @ 0x7ff049cc5300] decode_slice_header error
[h264 @ 0x7ff049ccfcc0] slice type 32 too large at 132120575
[h264 @ 0x7ff049ccfcc0] decode_slice_header error
[h264 @ 0x7ff04ba51bc0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba51bc0] decode_slice_header error
[h264 @ 0x7ff04ba51bc0] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba51bc0] decode_slice_header error
[h264 @ 0x7ff041d7dbc0] slice type 32 too large at 132120575
[h264 @ 0x7ff041d7dbc0] decode_slice_header error
[h264 @ 0x7ff041c9e480] slice type 32 too large at 132120575
[h264 @ 0x7ff041c9e480] decode_slice_header error
[h264 @ 0x7ff041ca9240] slice type 32 too large at 132120575
[h264 @ 0x7ff041ca9240] decode_slice_header error
[h264 @ 0x7ff041cb3a80] slice type 32 too large at 132120575
[h264 @ 0x7ff041cb3a80] decode_slice_header error
[h264 @ 0x7ff04ba05480] slice type 32 too large at 132120575
[h264 @ 0x7ff04ba05480] decode_slice_header error
[

KeyboardInterrupt: 

# label images using the labelimg software below

In [ ]:
!labelImg

# create the object detection model 

In [9]:
class ObjectDetection:
    def __init__(self, weights_path="source_code/dnn_model/yolov3_training_last_latest.weights", cfg_path="source_code/dnn_model/yolov3_training.cfg"):
        print("Loading Object Detection")
        print("Running opencv dnn with YOLOv3")
        #Filter duplicate bounding bounding boxes above a certain threshold. 
        self.nmsThreshold = 0.4
        #Detect boxes with probability / confidence over a certain threshold
        self.confThreshold = 0.5
        self.image_size = 608

        # Load Network
        net = cv2.dnn.readNet(weights_path, cfg_path)

        # Enable GPU CUDA
        net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
        net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
        self.model = cv2.dnn_DetectionModel(net)

        self.colors = np.random.uniform(0, 255, size=(80, 3))

        self.model.setInputParams(size=(self.image_size, self.image_size), scale=1/255)


    def detect(self, frame):
        return self.model.detect(frame, nmsThreshold=self.nmsThreshold, confThreshold=self.confThreshold)



# create the animation for a given video with the bounding box:
# ids - 0,1,2
# 0 - Toy, 1- Pig1 (with different ear tags), 2 - pig2 (same ear tags)

In [17]:
# import cv2
# import numpy as np
# from object_detection import ObjectDetection
import math

# Initialize Object Detection
od = ObjectDetection()

# cap = cv2.VideoCapture("pig_videos/Event20230919145449004.avi")

cap = cv2.VideoCapture("pig_videos/Event20230919160512004.avi")

# Initialize count
count = 0
center_points_prev_frame = []

tracking_objects = {}
track_id = 0

start_frame_number = 0

while True:
    start_frame_number += 50
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame_number)
    ret, frame = cap.read()
    count += 1
    if not ret:
        break
    print(count)
    # Point current frame
    center_points_cur_frame = []

    # Detect objects on frame
    (class_ids, scores, boxes) = od.detect(frame)
    print("class_ids:", class_ids)
    print("scores:", scores)
    print("boxes:", boxes)
    for i, box in enumerate(boxes):
        (x, y, w, h) = box
        cx = int((x + x + w) / 2)
        cy = int((y + y + h) / 2)
        center_points_cur_frame.append((cx, cy, class_ids[i]))
        #print("FRAME N°", count, " ", x, y, w, h)

        # cv2.circle(frame, (cx, cy), 5, (0, 0, 255), -1)
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
    #create the red point inside the box and the text
    for pt in center_points_cur_frame:
        point = (pt[0], pt[1])
        cv2.circle(frame, point, 5, (0, 0, 255), -1)
        cv2.putText(frame, str(pt[2]), (pt[0], pt[1] - 7), 0, 1, (0, 0, 255), 2)


    cv2.imshow("Frame", frame)

    # Make a copy of the points
    center_points_prev_frame = center_points_cur_frame.copy()

    key = cv2.waitKey(1)
    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()


Loading Object Detection
Running opencv dnn with YOLOv3


[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fde81a791c0] slice type 32 too large at 132120575
[h264 @ 0x7fde81a791c0] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[

1
class_ids: [1 2]
scores: [0.9983275 0.7929101]
boxes: [[ 880   15  376  257]
 [1271    8  148  273]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

2
class_ids: [1 2]
scores: [0.9969608 0.9880507]
boxes: [[ 882   26  388  243]
 [1270    0  156  255]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

3
class_ids: [1 2]
scores: [0.9970029 0.9777342]
boxes: [[ 876   23  395  258]
 [1270    0  159  256]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

4
class_ids: [1 2]
scores: [0.9971725 0.965166 ]
boxes: [[ 870   27  404  248]
 [1267    0  169  252]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

5
class_ids: [1 2]
scores: [0.99792314 0.9785829 ]
boxes: [[ 873   22  405  251]
 [1266    0  168  260]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

6
class_ids: [1 2]
scores: [0.9978695 0.9851521]
boxes: [[ 880   23  399  254]
 [1268    0  165  266]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

7
class_ids: [1 2]
scores: [0.9982281  0.98914737]
boxes: [[ 870   29  402  246]
 [1268    0  165  261]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

8
class_ids: [1 2]
scores: [0.9986131  0.98895836]
boxes: [[ 877   33  396  247]
 [1266    0  162  243]]
9


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

class_ids: [1 2]
scores: [0.99899405 0.98521197]
boxes: [[ 868   29  407  244]
 [1270    0  155  240]]
10


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

class_ids: [1 2]
scores: [0.9976758  0.84251595]
boxes: [[ 876   33  412  242]
 [1264    0  181  245]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

11
class_ids: [1 2]
scores: [0.9971311 0.8328367]
boxes: [[ 881    9  369  253]
 [1301   35  203  180]]
12


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

class_ids: [1 2]
scores: [0.9983551  0.91329587]
boxes: [[ 876   27  389  237]
 [1288   24  207  169]]
13


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

class_ids: [1 2]
scores: [0.99796015 0.93412197]
boxes: [[ 868   24  394  249]
 [1302    9  202  214]]
14


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

class_ids: [1 1]
scores: [0.996659 0.674694]
boxes: [[ 854   30  422  249]
 [1303   23  205  193]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

15
class_ids: [1 2]
scores: [0.99937546 0.97786134]
boxes: [[ 878   34  390  235]
 [1296   13  196  211]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

16
class_ids: [1 2]
scores: [0.9993757  0.98204505]
boxes: [[ 882   48  376  219]
 [1294   10  209  214]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

17
class_ids: [1 2]
scores: [0.99303657 0.95420146]
boxes: [[ 865   36  414  236]
 [1300   37  206  174]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

18
class_ids: [1 1]
scores: [0.9973076 0.8421321]
boxes: [[ 868   23  387  237]
 [1260   66  280  158]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

19
class_ids: [1 1]
scores: [0.9941206  0.81656224]
boxes: [[ 871   18  367  242]
 [1249   67  307  143]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

20
class_ids: [1 2]
scores: [0.9937205 0.986613 ]
boxes: [[ 888    8  349  248]
 [1302   37  205  219]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

21
class_ids: [1 2]
scores: [0.99701124 0.9895449 ]
boxes: [[ 869   15  403  248]
 [1311   34  181  259]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

22
class_ids: [1]
scores: [0.9909039]
boxes: [[1096  101  408  192]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

23
class_ids: [1]
scores: [0.9919916]
boxes: [[1115   79  368  219]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

24
class_ids: [2]
scores: [0.8063299]
boxes: [[1361   55  161  307]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

25
class_ids: [1 1]
scores: [0.9823714 0.9818566]
boxes: [[1098   20  324  178]
 [ 910  293  172  464]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

26
class_ids: [1 2]
scores: [0.92815113 0.8178534 ]
boxes: [[897  39 276 284]
 [854 404 154 393]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

27
class_ids: [2]
scores: [0.95525134]
boxes: [[913 160 158 378]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

28
class_ids: [1 2]
scores: [0.8170755 0.9275824]
boxes: [[531 503 379 487]
 [900 448 193 337]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

29
class_ids: [1 1]
scores: [0.8217439 0.5330137]
boxes: [[497 590 405 326]
 [671 639 319 377]]


[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f6b100] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f6b100] decode_slice_header error
[h264 @ 0x7fdf21f75400] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f75400] decode_slice_header error
[h264 @ 0x7fdf21f7f2c0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f7f2c0] decode_slice_header error
[h264 @ 0x7fdf21f85680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f85680] decode_slice_header error
[h264 @ 0x7fdf21f8d680] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f8d680] decode_slice_header error
[h264 @ 0x7fdf21f97440] slice type 32 too large at 132120575
[h264 @ 0x7fdf21f97440] decode_slice_header error
[h264 @ 0x7fdf21fa1200] slice type 32 too large at 132120575
[h264 @ 0x7fdf21fa1200] decode_slice_header error
[h264 @ 0x7fdf21faafc0] slice type 32 too large at 132120575
[h264 @ 0x7fdf21faafc0] decode_slice_header error
[

30


KeyboardInterrupt: 